print("Welcome to the tip calculator.")
bill = input("What was the total bill?\n£")
tip = input("What percentage tip would you like to give? 10, 12, or 15?\n%")
split = input("How many people to split the bill\n")
percentage_tip = 1 + (int(tip) / 100)
total_bill = ((float(bill)) * (float(percentage_tip)))
total = ((float(total_bill)) / ((float(split))))
final_amount = "{:.2f}".format(total)
print(f"Each person should pay: £{final_amount}")
